### ISSUE TITLE
Can I have early access to a pre-built build for a 64-bit Windows 11 PC?

### ISSUE THREAD

**Issue by PPPDUD** [FoxsDenYT/Flame-Next#4]
I am considering collaborating with you and promoting Flame Next, but I want to make sure that your browser is awesome. As a result, I request that you give me an early beta build built from the publicly available source code, and that you state that Flame Next is for _macOS_ and not Macs in general.

If you successfully perform the steps above and I believe that your browser is awesome, we can enter a collaboration, and Flame Next will become Mojavesoft's flagship desktop browser. Together, we can compete against Catalyst and Arc and get a high market share. Additionally, I can host backup copies of Flame Next on my servers, so that if Github goes out users can still download Flame Next.

**Comment by FoxsDenYT** [comment]
Hello PPPDUD, I am not looking for Collaboration/Promotion, as I do not think the browser is ready for the public as it is filled with bugs, and and currently undergoing a huge redesign.
I will consider it in the future.

**Comment by FoxsDenYT** [comment]
Heres the designs (use the menu in the top left to change versions):
https://www.figma.com/file/WQk4o72Gd85cnR2dFG0kZ9?embed_host=share&kind=&mode=design&node-id=1%3A2&t=dLomeNep2HdOsfE7-1&type=design&viewer=1

**Comment by FoxsDenYT** [comment]
also i doubt that github (and google drive) will go down and if they do, i have it stored on:
* My Thumbdrive
* My GoogleDrive
* My GitHub
so I am doubtful that I will need any other backups

**Comment by FoxsDenYT** [comment]
also what is Catalyst

**Comment by FoxsDenYT** [comment]
send a link to catalyst, please

**Comment by PPPDUD** [comment]
https://scratch.mit.edu/discuss/topic/672717/

**Comment by FoxsDenYT** [comment]
catalyst does not seem like it will eat up my market share. its not more popular than arc. its less popular
